nameOverride: ""

config:
  ### Wallarm API configuration
  ###
  api:
    ### Token to authorize in the Wallarm Cloud. Required.
    ###
    token: ""
    ### Address of Wallarm API service
    ###
    host: api.wallarm.com
    ### Port of Wallarm API service
    ###
    port: 443
    ### Use SSL to connect to Wallarm API service: `true` or `false`
    ###
    useSSL: true
    ### Verify CA during connecting to Wallarm API service: `true` or `false`
    ###
    caVerify: true

  mirroring:
    daemonSet:
      enabled: true
    vxlan:
      enabled: true

## Array of private container registry credentials
## https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
## Skipped yet. Will be valid ifter moving to GitLab
## CI and GitLab Container Registry
##
imagePullSecrets: []
# - name: secretName

processing:
  image:
    registry: "docker.io"
    name: "wallarm/node"
    tag: "4.2"
    pullPolicy: IfNotPresent

  ## Number of deployment replicas. Statefull
  ## https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#deploymentspec-v1-apps
  ##
  replicaCount: 1

  ## Settings for automated rolling updates
  ## https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#deploymentstrategy-v1-apps
  ##
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0%

  ## Labels to add to the pods
  ##
  podLabels: {}
  # key: value

  ## Annotations to add to the pods
  ##
  podAnnotations: {}
  # key: value

  ## Additional environment variables to pass to the paperless container
  ##
  extraEnvs: []
  # - name: FOO
  #   value: FOO
  # - name: BAR
  #   valueFrom:
  #     secretKeyRef:
  #       key: BAR
  #       name: bar-secret

  ## Setting to allow this Pod to schedule onto nodes with matching taints
  ## https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  ##
  tolerations: []
  # - key: "key"
  #   operator: "Equal|Exists"
  #   value: "value"
  #   effect: "NoSchedule|PreferNoSchedule"

  ## Affinity and anti-affinity settings of this Pod
  ## https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  ## Prefered podAntiAffinity will be applied if no one affinity configured
  ##
  affinity: {}
  # podAntiAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #   - weight: 100
  #     podAffinityTerm:
  #       labelSelector:
  #         matchExpressions:
  #         - key: component
  #           operator: In
  #           values:
  #           - mtls-router
  #         - key: app
  #           operator: In
  #           values:
  #           - mtls-router
  #       topologyKey: kubernetes.io/hostname

  ## Node selector (node labels) for pods
  ## https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

  ## Lifecycle hooks
  ## https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  ##
  lifecycle: {}

  ## Grace period for the pods termination in seconds
  ##
  terminationGracePeriodSeconds: 30

  ## PriorityClass name to apply to the pods
  ## This setting indicates the importance of the pod relative to other pods
  ## https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
  ##
  priorityClassName: ""

  ## Privilegues and access controls for the the container
  ## https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ## https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#securitycontext-v1-core
  ##
  securityContext: {}

  ## The number of resources required for the main container
  ## https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  ##
  resources: {}
  # requests:
  #   memory: 1Gi
  #   cpu: 500m
  # limits:
  #   memory: 1Gi
  #   cpu: 1000m

  livenessProbe: {}
    # httpGet:
    #   path: /accounts/login/
    #   port: http
    #   httpHeaders:
    #     - name: Host
    #       value: localhost
    # initialDelaySeconds: 150
    # periodSeconds: 15
    # timeoutSeconds: 3
    # failureThreshold: 3
    # successThreshold: 1

  readinessProbe:
    httpGet:
      path: /accounts/login/
      port: http
      httpHeaders:
        - name: Host
          value: localhost
    initialDelaySeconds: 90
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1

  ## Additional containers for this pods
  ##
  extraContainers: []
  # - name: some-container
  #   image: some/image:latest
  #   env:
  #   - name: FOO
  #     value: "123"
  #   volumeMounts:
  #   - name: bar-volume
  #     mountPath: /mnt

  ## Additional init containers
  ##
  extraInitContainers: []
  # - name: init
  #   image: busybox
  #   command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']

  ## Additional volumes that should be mounted to the main container
  ##
  extraVolumeMounts: []
  # - name: something
  #   mountPath: /mnt/something

  ## Volumes that should attached to pods
  ##
  extraVolumes: []
  # - name: something
  #   emptyDir: {}

  service:
    ## Service type
    ## https://kubernetes.io/docs/concepts/services-networking/service/
    ## https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#service-v1-core
    ##
    type: ClusterIP

    ## Service port
    ##
    port: 80

    ## Service node port (if the service type if "NodePort")
    ##
    nodePort: 0

    ## Load balancer IP address
    ## https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
    ##
    loadBalancerIP: ""

    ## Load balancer source ranges. Helpful for EKS/GKE/AKE
    ## https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support
    ##
    loadBalancerSourceRanges: []
    # - "192.168.0.0/16"
    # - "10.0.0.0/8"
    # - "172.16.0.0/12"

    ## Kubernetes external traffic policy
    ## https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/
    ##
    externalTrafficPolicy: ""

    ## Annotations for this Service
    ##
    annotations: {}

    ## IP address of this Service cluster
    ##
    clusterIP: ""

    ## ExternalIPs is a list of IP addresses for which nodes in the cluster will also accept traffic
    ## for this service. These IPs are not managed by Kubernetes.
    ##
    externalIPs: []

  ## Pod Disturion Budget settings
  ## https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  ##
  podDisruptionBudget:
    enabled: true

    ### Select only one of these:
    maxUnavailable: 1
    # minAvailable: 1

  ## Autoscaling
  ## https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  ##
  autoscaling:
    enabled: false

    ## Scaling thresholds, min and max
    ##
    minReplicas: 1
    maxReplicas: 3

    ## Target average values of the metric across all relevant pods, represented
    ## as a percentage of the requested value of the resource for the pods.
    ##
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 85


## Aggregation module deployment configuration.
aggregation:
  image:
    registry: "docker.io"
    name: "wallarm/node"
    tag: "4.2"
    pullPolicy: IfNotPresent

  ## Number of deployment replicas
  ## https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#deploymentspec-v1-apps
  ##
  replicaCount: 1

  ## Settings for automated rolling updates
  ## https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#deploymentstrategy-v1-apps
  ##
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0%

  ## Labels to add to the pods
  ##
  podLabels: {}
  # key: value

  ## Annotations to add to the pods
  ##
  podAnnotations: {}
  # key: value

  ## Additional arguments to pass to the gotenberg container
  ##
  extraArgs: []

  ## Additional environment variables to pass to the gotenberg container
  ##
  extraEnvs: []
  # - name: FOO
  #   value: FOO
  # - name: BAR
  #   valueFrom:
  #     secretKeyRef:
  #       key: BAR
  #       name: bar-secret

  ## Setting to allow this Pod to schedule onto nodes with matching taints
  ## https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  ##
  tolerations: []
  # - key: "key"
  #   operator: "Equal|Exists"
  #   value: "value"
  #   effect: "NoSchedule|PreferNoSchedule"

  ## Affinity and anti-affinity settings of this Pod
  ## https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  ## Prefered podAntiAffinity will be applied if no one affinity configured
  ##
  affinity: {}
  # podAntiAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #   - weight: 100
  #     podAffinityTerm:
  #       labelSelector:
  #         matchExpressions:
  #         - key: component
  #           operator: In
  #           values:
  #           - mtls-router
  #         - key: app
  #           operator: In
  #           values:
  #           - mtls-router
  #       topologyKey: kubernetes.io/hostname

  ## Node selector (node labels) for pods
  ## https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

  ## Lifecycle hooks
  ## https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  ##
  lifecycle: {}

  ## Grace period for the pods termination in seconds
  ##
  terminationGracePeriodSeconds: 30

  ## PriorityClass name to apply to the pods
  ## This setting indicates the importance of the pod relative to other pods
  ## https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
  ##
  priorityClassName: ""

  ## Privilegues and access controls for the the container
  ## https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ## https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#securitycontext-v1-core
  ##
  securityContext: {}

  ## The number of resources required for the main container
  ## https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  ##
  resources: {}
  # requests:
  #   memory: 256Mi
  #   cpu: 250m
  # limits:
  #   memory: 512Mi
  #   cpu: 500m

  livenessProbe: {}
    # exec:
    #   command: [ "/usr/bin/env", "bash", "/opt/liveness.sh" ]
    # initialDelaySeconds: 60
    # timeoutSeconds: 3
    # periodSeconds: 15
    # failureThreshold: 3
    # successThreshold: 1

  readinessProbe: {}
    # exec:
    #   command: [ "/usr/bin/env", "bash", "/opt/readiness.sh" ]
    # initialDelaySeconds: 60
    # timeoutSeconds: 3
    # periodSeconds: 15
    # failureThreshold: 3
    # successThreshold: 1

  service:
    ## Service type
    ## https://kubernetes.io/docs/concepts/services-networking/service/
    ## https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#service-v1-core
    ##
    type: ClusterIP

    ## Service port
    ##
    port: 3313

    ## Service node port (if the service type if "NodePort")
    ##
    nodePort: 0

    ## Load balancer IP address
    ## https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
    ##
    loadBalancerIP: ""

    ## Load balancer source ranges. Helpful for EKS/GKE/AKE
    ## https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support
    ##
    loadBalancerSourceRanges: []
    # - "192.168.0.0/16"
    # - "10.0.0.0/8"
    # - "172.16.0.0/12"

    ## Kubernetes external traffic policy
    ## https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/
    ##
    externalTrafficPolicy: ""

    ## Annotations for this Service
    ##
    annotations: {}

    ## IP address of this Service cluster
    ##
    clusterIP: ""

    ## ExternalIPs is a list of IP addresses for which nodes in the cluster will also accept traffic
    ## for this service. These IPs are not managed by Kubernetes.
    ##
    externalIPs: []

  ## Pod Disturion Budget settings
  ## https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  ##
  podDisruptionBudget:
    enabled: true

    ### Select only one of these:
    maxUnavailable: 0
    # minAvailable: 1

  ## Autoscaling
  ## https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  ##
  autoscaling:
    enabled: false

    ## Scaling thresholds, min and max
    ##
    minReplicas: 1
    maxReplicas: 3

    ## Target average values of the metric across all relevant pods, represented
    ## as a percentage of the requested value of the resource for the pods.
    ##
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 85

  ## Additional containers for this pods
  ##
  extraContainers: []
  # - name: some-container
  #   image: some/image:latest
  #   env:
  #   - name: FOO
  #     value: "123"
  #   volumeMounts:
  #   - name: bar-volume
  #     mountPath: /mnt

  ## Additional init containers
  ##
  extraInitContainers: []
  # - name: init
  #   image: busybox
  #   command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']

  ## Additional volumes that should be mounted to the main container
  ##
  extraVolumeMounts: []
  # - name: something
  #   mountPath: /mnt/something

  ## Volumes that should be attached to pods
  ##
  extraVolumes: []
  # - name: something
  #   emptyDir: {}

  extraLabels: {}
  extraAnnotations: {}

## Service Account for this Pod
## https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  create: true

  ## Name of the ServiceAccount. If creating not required then
  ## this name must be name of existing ServiceAccount object
  ##
  name: ""

  ## Annotations for the created Service Account
  ##
  annotations: {}

extraLabels: {}
extraAnnotations: {}
