{{- if .Values.agent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "agent.serviceAccountName" . }}
  annotations:
    {{- include "agent.annotations" . | nindent 4 }}
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-10"
    {{- with .Values.agent.serviceAccount.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
{{- end -}}
