{{- if .Values.processing.podDisruptionBudget }}
{{- if .Values.processing.podDisruptionBudget.enabled }}
apiVersion: {{ template "podDisruptionBudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "processing.fullname" . }}
  annotations:
    {{- include "wallarm-oob.annotations" . | nindent 4 }}
  labels:
    {{- include "processing.labels" . | nindent 4 }}
    app.kubernetes.io/component: "processing"
spec:
  selector:
    matchLabels:
      {{- include "processing.selectorLabels" . | nindent 6 }}
  {{- with .Values.processing.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  {{- with .Values.processing.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
