processing:
  replicaCount: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
aggregation:
  replicaCount: 2
  resources:
     requests:
       memory: 256Mi
       cpu: 250m
     limits:
       memory: 512Mi
       cpu: 500m