apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "aggregation.fullname" . }}
  annotations:
    {{- include "wallarm-oob.annotations" . | nindent 4 }}
    {{- with .Values.aggregation.extraAnnotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "aggregation.labels" . | nindent 4 }}
    {{- with .Values.aggregation.extraLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.aggregation.replicaCount }}
  {{- with .Values.aggregation.updateStrategy }}
  strategy: {{ . | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aggregation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "wallarm-oob.annotations" . | nindent 8 }}
        {{- with .Values.aggregation.podAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- with .Values.aggregation.extraAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "aggregation.labels" . | nindent 8 }}
        {{- with .Values.aggregation.podLabels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- with .Values.aggregation.extraLabels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.aggregation.terminationGracePeriodSeconds | default 30 }}
      {{- with .Values.aggregation.nodeSelector }}
      nodeSelector: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.aggregation.tolerations }}
      tolerations: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.aggregation.affinity }}
      affinity: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.aggregation.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.aggregation.extraInitContainers }}
      initContainers: {{ . | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: tarantool
        image: {{ include "image" .Values.aggregation.image }}
        imagePullPolicy: {{ .Values.aggregation.image.pullPolicy }}
        args:
          {{- with .Values.aggregation.extraArgs }}
          {{ . | toYaml | nindent 10 }}
          {{- end -}}
        {{- with .Values.aggregation.extraEnvs }}
        env:
          - name: POSTANALYTIC_ONLY
            value: "true"
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        ports:
          - name: tarantool
            containerPort: 3313
            protocol: TCP
        {{- with .Values.aggregation.livenessProbe }}
        livenessProbe: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.aggregation.readinessProbe }}
        readinessProbe: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.aggregation.lifecycle }}
        lifecycle: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.aggregation.securityContext }}
        {{- with .Values.aggregation.securityContext }}
        securityContext: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- else }}
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_RAW
        {{- end }}
        {{- with .Values.aggregation.resources }}
        resources: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.aggregation.extraVolumeMounts }}
        volumeMounts:
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- with .Values.aggregation.extraContainers }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      {{- with .Values.aggregation.extraVolumes }}
      volumes:
      {{- . | toYaml | nindent 6 }}
      {{- end }}