apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "processing.fullname" . }}-paperless
  annotations:
    {{- include "processing.annotations" . | nindent 4 }}
  labels:
    {{- include "processing.labels" . | nindent 4 }}
    app.kubernetes.io/component: "paperless"
spec:
  replicas: {{ .Values.processing.replicaCount }}
  {{- with .Values.processing.updateStrategy }}
  strategy: {{ . | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "processing.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "paperless"
  template:
    metadata:
      annotations:
        {{- include "processing.annotations" . | nindent 8 }}
        {{- with .Values.processing.podAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "processing.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "paperless"
        {{- with .Values.processing.podLabels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "processing.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.processing.terminationGracePeriodSeconds | default 30 }}
      {{- with .Values.processing.nodeSelector }}
      nodeSelector: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.processing.tolerations }}
      tolerations: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.processing.affinity }}
      affinity: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.processing.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.processing.extraInitContainers }}
      initContainers: {{ . | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: paperless
        image: {{ include "processing.image" .Values.processing.image }}
        imagePullPolicy: {{ .Values.processing.image.pullPolicy }}
        env:
        {{- include "processing.envs.paperless" . | nindent 8 }}
        {{- include "processing.envs.postgres" . | nindent 8 }}
        {{- include "processing.envs.redis" . | nindent 8 }}
        {{- with .Values.processing.extraEnvs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        ports:
          - name: http
            containerPort: 8000
        {{- with .Values.processing.livenessProbe }}
        livenessProbe: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.processing.readinessProbe }}
        readinessProbe: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.processing.lifecycle }}
        lifecycle: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.processing.securityContext }}
        {{- with .Values.processing.securityContext }}
        securityContext: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- else }}
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
            add:
              - CHOWN
              - SETUID
              - SETGID
        {{- end }}
        {{- with .Values.processing.resources }}
        resources: {{ . | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /usr/src/paperless/data
          subPath: data
        - name: data
          mountPath: /usr/src/paperless/media
          subPath: media
        - name: data
          mountPath: /usr/src/paperless/export
          subPath: export
        - name: data
          mountPath: /usr/src/paperless/consume
          subPath: consume
        {{- with .Values.processing.extraVolumeMounts }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- with .Values.processing.extraContainers }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
      {{- if .Values.processing.persistentVolumeClaim.create }}
          claimName: {{ include "processing.fullname" . }}-paperless
      {{- else }}
          claimName: {{ .Values.processing.persistentVolumeClaim.useExisting }}
      {{- end }}
      {{- with .Values.processing.extraVolumes }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
