{{- if .Values.processing.podDisruptionBudget }}
{{- if .Values.processing.podDisruptionBudget.enabled }}
apiVersion: {{ template "podDisruptionBudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "processing.fullname" . }}-paperless
  annotations:
    {{- include "processing.annotations" . | nindent 4 }}
  labels:
    {{- include "processing.labels" . | nindent 4 }}
    app.kubernetes.io/component: "paperless"
spec:
  selector:
    matchLabels:
      {{- include "processing.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "paperless"
  {{- with .Values.processing.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  {{- with .Values.processing.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
