apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "processing.fullname" . }}
  annotations:
    {{- include "processing.annotations" . | nindent 4 }}
  labels:
    {{- include "processing.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.processing.replicaCount }}
  {{- with .Values.processing.updateStrategy }}
  strategy: {{ . | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "processing.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ index (include (print .Template.BasePath "/processing-configmap.yaml") . | fromYaml) "data" | toYaml | sha256sum }}
        checksum/credentials: {{ index (include (print .Template.BasePath "/shared-secret.yaml") . | fromYaml) "data" | toYaml | sha256sum }}
        {{- include "processing.annotations" . | nindent 8 }}
        {{- with .Values.processing.podAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "processing.labels" . | nindent 8 }}
        {{- with .Values.processing.podLabels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.processing.serviceAccount.create }}
      serviceAccountName: {{ template "processing.serviceAccountName" . }}
      {{- else }}
      automountServiceAccountToken: false
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.processing.terminationGracePeriodSeconds | default 30 }}
      {{- with .Values.processing.nodeSelector }}
      nodeSelector: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.processing.tolerations }}
      tolerations: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.processing.affinity }}
      affinity: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.processing.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.processing.extraInitContainers }}
      initContainers: {{ . | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: processing
        image: {{ include "image" .Values.processing.image }}
        imagePullPolicy: {{ .Values.processing.image.pullPolicy }}
        args:
          {{- with .Values.processing.extraArgs }}
          {{ . | toYaml | nindent 10 }}
          {{- end }}
        env:
        - name: NGINX_EXTERNAL_CONFIG
          value: "true"
        - name: POSTANALYTIC_ADDRESS
          value: {{ printf "%s.%s.svc" (include "aggregation.fullname" .) .Release.Namespace }}
        {{- include "wallarm-oob.credentials" . | nindent 8 }}
        {{- with .Values.processing.extraEnvs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        ports:
          - name: http
            containerPort: 8445
            protocol: TCP
          - name: metrics
            containerPort: {{ .Values.config.processing.metricsPort }}
            protocol: TCP
        {{- with .Values.processing.livenessProbe }}
        livenessProbe: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.processing.readinessProbe }}
        readinessProbe: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.processing.lifecycle }}
        lifecycle: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.processing.securityContext }}
        securityContext: {{ .Values.processing.securityContext | toYaml | nindent 10 }}
        {{- else }}
        securityContext: {{ include "wallarm-oob.nodeSecurityContext" . | nindent 10 }}
        {{- end }}
        {{- with .Values.processing.resources }}
        resources: {{ . | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
        {{- with .Values.processing.extraVolumeMounts }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- with .Values.processing.extraContainers }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ template "processing.fullname" . }}
      {{- with .Values.processing.extraVolumes }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
