apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wallarm-oob.sharedSecretName" . }}
  annotations:
    {{- include "wallarm-oob.annotations" . | nindent 4 }}
  labels:
    {{- include "wallarm-oob.labels" . | nindent 4 }}
type: Opaque
data:
  WALLARM_API_TOKEN: {{ .Values.config.api.token | b64enc | quote }}
  WALLARM_API_HOST: {{ .Values.config.api.host | b64enc | quote }}
  WALLARM_API_PORT: {{ .Values.config.api.port | toString | b64enc | quote }}
  WALLARM_API_USE_SSL: {{ .Values.config.api.useSSL | toString | b64enc | quote }}
  WALLARM_API_CA_VERIFY: {{ .Values.config.api.caVerify | toString | b64enc | quote }}
