name: CI

on:
  pull_request:
    branches: ['main']
    types: ['opened', 'reopened', 'synchronize']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  changes:
    name: Changes
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      helm: ${{ steps.filter.outputs.helm}}
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.0.2

      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.10.2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            helm:
              - 'helm/Chart.yaml'
              - 'helm/**/*'

  smoke:
    name: Smoke
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.helm == 'true'
    env:
      KUBECONFIG: ${{ env.HOME }}/kube/kind-config-kind
    strategy:
      matrix:
        k8s: [v1.23.13, v1.24.7, v1.25.3]
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.0.2

      - name: Install helm
        uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82
        with:
          version: 'v3.8.0'

      - name: Create cluster
        uses: helm/kind-action@9e8295d178de23cbfbd8fa16cf844eec1d773a07
        with:
          version: v0.17.0
          cluster_name: kind
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Get cluster config
        run: kind get kubeconfig > ${KUBECONFIG}

      - name: Install chart
        env:
          WALLARM_API_TOKEN: ${{ secrets.WALLARM_API_TOKEN }}
        run: make helm-install

      - name: Run smoke tests
        env:
          KIND_CLUSTER_NAME: kind
          USER_UUID: ${{ secrets.WALLARM_API_USER_UUID }}
          USER_SECRET: ${{ secrets.WALLARM_API_USER_SECRET }}
          CLIENT_ID: 4
        run: |
          echo ${{ secrets.GITLAB_TOKEN_SECRET }} | docker login -u ${{ secrets.GITLAB_TOKEN_NAME }} --password-stdin dkr.wallarm.com
          make smoke-test

  helm-install:
    name: Helm install
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.helm == 'true'
    env:
      KUBECONFIG: ${{ env.HOME }}/kube/kind-config-kind
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.0.2

      - name: Install helm
        uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82
        with:
          version: 'v3.8.0'

      - name: Create cluster
        uses: helm/kind-action@9e8295d178de23cbfbd8fa16cf844eec1d773a07
        with:
          version: v0.17.0
          cluster_name: kind
          node_image: kindest/node:v1.24.7

      - name: Get cluster config
        run: kind get kubeconfig > ${KUBECONFIG}

      - name: Run chart tests
        env:
          WALLARM_API_TOKEN: ${{ secrets.WALLARM_API_TOKEN }}
        run: make helm-test


